### ISSUE TITLE
I ran the script but the Username and password are not working?

### ISSUE THREAD

**Issue by TheJoe1990** [malordin/steamdeck-samba-server#1]
After running the script if I navigate to SMB within the steamdeck the desired folders show up.  However, when I attempt to navigate to \\steamdeck or the IP address of the steamdeck I am prompted for the username and password, where I get stuck.  

I have double checked I am using the correct password that I set within the steamdeck, and the username should be deck?  

Am I missing something silly?

**Comment by TheJoe1990** [comment]
I reran the script and set the samba password to something else and still no luck.  I dont understand.

**Comment by malordin** [comment]
> I reran the script and set the samba password to something else and still no luck. I dont understand.

Hi!

It is important to understand that the login and password of the folders distributed by the samba server are **different** and do not depend on the "deck" account on the steam deck itself. I made the login the same as I did on the Linux system on the steam deck just for the sake of convenience so that I don't have to remember 2 different logins.

So, the default login is "**deck**" and the password needs to be entered when running the script. It just asks "Please enter your password" and then you have to enter the password for the samba server account and not the steam deck account. But to avoid the hassle, I usually put the same one as the user "deck" on the steam deck itself.

Please try it for testing purposes:

1. Run the script again.
2. enter the password "**12345678**" when asked.
3. go into explorer \\(ip-adress-of-steam-deck)
4. when it asks for username and password, enter "**deck**" in the login and "**12345678**" in the password.

Anyway, will it work or not, it would be great if you can tell me about it, I will wait for a reply, thanks!

**Comment by TheJoe1990** [comment]
Before your reply I added this to the config: `ntlm auth = true` (May or may not have affected anything) and it still didnt work, then I told it to reboot from within the terminal (Dont know if the method of reboot matters)

After the reboot it worked perfectly.  Thank you for making this, as much as I would love to reset everything and test it for you, its working now and I dont want to break it lol.

**Comment by malordin** [comment]
Well, glad it's working! Thanks for sharing.
